name: flipper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 99.99.99+99

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_login: 
    path:
      'packages/flipper_login'
  universal_platform: 1.0.0-nullsafety
  animations: ^2.0.0
  # sized_context: ^0.2.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  injectable: ^1.2.0
  http: ^0.13.0
  get_it: ^6.0.0
  flipper_services:
    path:
      'packages/flipper_services'
  flipper_chat:
    path:
      'packages/flipper_chat'
  flipper_dashboard:
    path:
      'packages/flipper_dashboard'
  firebase_messaging: ^9.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  camera: ^0.8.0
  auto_route:
  awesome_notifications:
  geolocator:
  permission_handler:
  built_value:
  image_picker:
  built_collection:
  flutter_image_compress: 1.0.0-nullsafety
  jiffy: 
  expandable:
  timezone: 0.7.0-nullsafety.0
  cupertino_icons:
  get_storage:
  country_picker:
  # pusher_beams: not available for null safe
  # firebase_analytics: not available
  # flutter_uploader: not available
  rxdart:
  # loading: not available
  firebase_crashlytics: 
  logger:
  async:
  stacked: 
  stacked_hooks:
  stacked_services: 0.8.0-nullsafety.1
  provider:
  cached_network_image: 3.0.0-nullsafety
  flutter_dotenv: 4.0.0-nullsafety.0
  mailer:
  # contacts_service: not available
  connectivity:
  # bluetooth_thermal_printer: not available
  # firebase_remote_config: not available
  # esc_pos_utils: not available
  # pusher: not available
  get: 4.0.0-nullsafety.2
  flutter_slidable: 
  in_app_review:
  timeago:
  cron:
  number_display: ^3.0.0
  # firebase_dynamic_links: not available
  
  bitsdojo_window: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  auto_route_generator: 
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  # flutter run
  # flutter create --template=package hello
  # ./flutterw packages pub run build_runner build --delete-conflicting-outputs
